// src/services/at5ParameterManifest.ts
// Maps AI/debug-friendly gear settings into AT5 XML-safe parameter attributes.

import {
  AMP_MANIFEST,
  STOMP_MANIFEST,
  CAB_MANIFEST,
  RACK_MANIFEST,
  ROOM_MANIFEST,
  TONEX_MANIFEST,
  GearItem,
  KnobDefinition,
} from "./gearManifest";
import { AT5_VERIFIED_GEAR, VerifiedGearDef, VerifiedParamDef } from "./at5VerifiedParameterOverrides";
import { getAt5Catalog, cleanGearNameForMatching } from "./at5Catalog";
import { ParameterMapping, MicPlacementMapping, ParameterOptionRow } from "../types";
import { at5DatabaseService } from "./at5DatabaseService";

let dbParameterMappings: ParameterMapping[] = [];
let dbMicPlacementMappings: MicPlacementMapping[] = [];

export async function refreshDbParameterMappings(): Promise<void> {
  try {
    dbParameterMappings = await at5DatabaseService.getParameterMappings() || [];
    dbMicPlacementMappings = await at5DatabaseService.getMicPlacementMappings() || [];
  } catch (error) {
    console.error("Failed to refresh db parameter mappings", error);
  }
}

export function getDbParameterMappings(): ParameterMapping[] {
  return dbParameterMappings;
}

export function getDbMicPlacementMappings(): MicPlacementMapping[] {
  return dbMicPlacementMappings;
}

export function setDbMicPlacementMappings(mappings: MicPlacementMapping[]): void {
  dbMicPlacementMappings = mappings;
}


export const FILTER_BANDS = [
  20, 25, 31, 40, 50, 63, 80, 100, 125, 160, 200, 250, 315, 400, 500, 630, 
  800, 1000, 1250, 1600, 2000, 2500, 3150, 4000, 5000, 6300, 8000, 10000, 
  12500, 16000, 20000
];

export function parseFrequencyToHz(freqStr: string): number | null {
  const clean = freqStr.toLowerCase().trim();
  const match = clean.match(/^([0-9.]+)\s*(khz|hz|k)?$/);
  if (!match) return null;
  const val = parseFloat(match[1]);
  if (isNaN(val)) return null;
  const unit = match[2];
  if (unit === "khz" || unit === "k") {
    return val * 1000;
  }
  return val;
}

export function findClosestBand(hz: number): number {
  let closest = FILTER_BANDS[0];
  let minDiff = Math.abs(hz - closest);
  for (let i = 1; i < FILTER_BANDS.length; i++) {
    const diff = Math.abs(hz - FILTER_BANDS[i]);
    if (diff < minDiff) {
      minDiff = diff;
      closest = FILTER_BANDS[i];
    }
  }
  return closest;
}

export interface ResolvedParameter {
  friendlyName: string;
  xmlName: string;
  min: number;
  max: number;
  unit?: string;
  aliases?: string[];
  savedAliases?: string[];
  rawMappingAliases?: string[];
  autoGeneratedAliases?: string[];
  effectiveAliases?: string[];
  defaultValue?: number | string;
  transform?: VerifiedParamDef["transform"] | string;
  visualMin?: number;
  visualMax?: number;
  kind?: "continuous_knob" | "switch_boolean" | "enum" | "frequency" | "gain_db" | "time_ms" | "semantic";
  definitionSource?: "db_mapping" | "verified_override" | "catalog_explicit" | "catalog_fallback" | "generic_fallback";
  authoritativeRange?: [number, number];

  // Extended fields
  gearGuid?: string;
  displayParameterName?: string;
  canonicalParameterName?: string;
  at5XmlAttributeName?: string;
  interfaceType?: 'knob' | 'slider' | 'switch' | 'selector' | 'enum' | 'text' | 'reference' | 'hidden_default';
  parameterKind?: 'continuous' | 'boolean' | 'selector' | 'enum' | 'time' | 'frequency' | 'gain_db' | 'percentage' | 'xml_reference' | 'unsupported';
  displayMin?: number;
  displayMax?: number;
  displayUnit?: string;
  displayStep?: number;
  decimalPlaces?: number;
  displayPrecision?: number;
  displayDecimalPlaces?: number;
  defaultDisplayValue?: string | number;
  exportUnit?: string;
  exportStep?: number;
  exportDecimalPlaces?: number;
  exportPrecision?: number;
  defaultExportValue?: string | number;
  translationMode?: string;
  valueMap?: Record<string, string | number>;
  reverseValueMap?: Record<string, string>;
  helperDescription?: string;
  exampleInput?: string;
  exampleOutput?: string;
  mappingConfidence?: 'high' | 'medium' | 'low';
  source?: 'at5p_discovery' | 'gear_manager_manual' | 'ikmpak_candidate' | 'inferred' | 'default';
  doNotRequestForGear?: boolean;
  unsupportedReason?: string;
  reviewNotes?: string;
  optionRows?: ParameterOptionRow[];
  valueMapJson?: string;
  reverseValueMapJson?: string;
}

const ALL_GEAR: GearItem[] = [
  ...AMP_MANIFEST,
  ...STOMP_MANIFEST,
  ...CAB_MANIFEST,
  ...RACK_MANIFEST,
  ...ROOM_MANIFEST,
  ...TONEX_MANIFEST,
];

export const normalise = (value: string) =>
  String(value)
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .trim();

export function generateAliasesForXmlParam(xmlName: string): string[] {
  const aliases = new Set<string>();
  aliases.add(xmlName);
  
  let base = xmlName;
  if (xmlName.includes("_")) {
    base = xmlName.split("_")[0];
  }
  
  const baseLower = base.toLowerCase().trim();
  aliases.add(base);
  
  const mapping: Record<string, string[]> = {
    drive: ["drive", "gain", "lead drive", "lead gain", "input drive"],
    volume: ["volume", "channel volume", "output volume"],
    master: ["master", "master volume"],
    treble: ["treble", "high", "highs"],
    bass: ["bass", "low", "lows"],
    middle: ["middle", "mid", "mids", "midrange"],
    presence: ["presence"],
    reverb: ["reverb"],
    bright: ["bright", "bright switch"],
    trebleshift: ["shift (treble)", "treble shift", "pull treble", "treble pull", "shift_treble", "shift treble"],
    bassshift: ["shift (bass)", "bass shift", "pull bass", "bass pull", "shift_bass", "shift bass"],
    rhythm2: ["rhythm 2", "rhythm2", "r2", "channel 2"],
    deep: ["deep", "deep switch"],
    eq: ["eq", "graphic eq", "eq on", "geq"],
    band80hz: ["80hz", "band 80", "eq 80hz", "80 hz", "80"],
    band240hz: ["240hz", "band 240", "eq 240hz", "240 hz", "240"],
    band750hz: ["750hz", "band 750", "eq 750hz", "750 hz", "750"],
    band2200hz: ["2200hz", "2.2khz", "band 2200", "eq 2200hz", "2.2 khz", "2200"],
    band6600hz: ["6600hz", "6.6khz", "band 6600", "eq 6600hz", "6.6 khz", "6600"]
  };

  if (mapping[baseLower]) {
    mapping[baseLower].forEach(a => aliases.add(a));
  }
  
  if (baseLower.endsWith("shift")) {
    const prefix = baseLower.substring(0, baseLower.length - 5);
    aliases.add(`${prefix} shift`);
    aliases.add(`shift (${prefix})`);
    aliases.add(`pull ${prefix}`);
    aliases.add(`${prefix} pull`);
  }
  
  if (baseLower.startsWith("band")) {
    const num = baseLower.substring(4);
    aliases.add(num);
    aliases.add(`band ${num}`);
    aliases.add(`eq ${num}`);
  }

  return Array.from(aliases);
}

const compact = (value: string) => String(value).replace(/[^a-zA-Z0-9]/g, "");

const escapeXmlAttr = (value: unknown) =>
  String(value).replace(/[<>&"']/g, (c) => {
    switch (c) {
      case "<": return "&lt;";
      case ">": return "&gt;";
      case "&": return "&amp;";
      case '"': return "&quot;";
      case "'": return "&apos;";
      default: return c;
    }
  });

const isKnobDefinition = (knob: string | KnobDefinition): knob is KnobDefinition =>
  typeof knob !== "string";

const scoreTextMatch = (query: string, candidates: string[]) => {
  const q = normalise(query);
  let score = 0;

  for (const rawCandidate of candidates) {
    const candidate = normalise(rawCandidate);
    if (!candidate) continue;

    if (candidate === q) score += 1000;
    if (candidate.includes(q)) score += 300;
    if (q.includes(candidate)) score += 180;

    for (const token of q.split(" ")) {
      if (token.length >= 3 && candidate.includes(token)) score += 20;
    }
  }

  return score;
};

export function findVerifiedGearWithScore(
  gearNameOrId: string | undefined,
  category?: string
): { gear: VerifiedGearDef; score: number } | undefined {
  if (!gearNameOrId) return undefined;

  const matches = AT5_VERIFIED_GEAR
    .filter((gear) => !category || gear.category === (category === "pedal" ? "stomp" : category))
    .map((gear) => ({
      gear,
      score: scoreTextMatch(gearNameOrId, [gear.name, gear.realId ?? "", ...(gear.aliases ?? [])]),
    }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);

  return matches[0];
}

export function findManifestGearWithScore(
  gearNameOrId: string | undefined,
  category?: string
): { gear: GearItem; score: number } | undefined {
  if (!gearNameOrId) return undefined;

  const matches = ALL_GEAR
    .filter((gear) => !category || gear.category === (category === "pedal" ? "stomp" : category))
    .map((gear) => ({
      gear,
      score: scoreTextMatch(gearNameOrId, [gear.id, gear.name, gear.realId ?? ""]),
    }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);

  return matches[0];
}

export function findCatalogGearWithScore(
  gearNameOrId: string | undefined,
  category?: string
): { gear: any; score: number } | undefined {
  if (!gearNameOrId) return undefined;

  const catalog = getAt5Catalog() || [];
  const group = category === "pedal" ? "stomp" : category;

  const matches = catalog
    .filter((item) => !group || item.group === group)
    .map((item) => {
      let score = scoreTextMatch(gearNameOrId, [
        item.displayName,
        item.guid ?? "",
        ...(item.otherNames ?? []),
        ...(item.examplePresets ?? [])
      ]);

      // Grant a substantial bonus for items with non-empty/real GUIDs to resolve tie-breakers nicely
      if (score > 0 && item.guid && item.guid.trim() !== "") {
        score += 500;
      }

      return { gear: item, score };
    })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score);

  return matches[0];
}

export function findVerifiedGear(
  gearNameOrId: string | undefined,
  category?: string
): VerifiedGearDef | undefined {
  const match = findVerifiedGearWithScore(gearNameOrId, category);
  return (match && match.score >= 150) ? match.gear : undefined;
}

export function findManifestGear(
  gearNameOrId: string | undefined,
  category?: string
): GearItem | undefined {
  const match = findManifestGearWithScore(gearNameOrId, category);
  return (match && match.score >= 150) ? match.gear : undefined;
}

export function resolveVerifiedOrManifestRealId(
  gearNameOrId: string | undefined,
  category?: string
): string | undefined {
  const verifiedMatch = findVerifiedGearWithScore(gearNameOrId, category);
  const manifestMatch = findManifestGearWithScore(gearNameOrId, category);
  const catalogMatch = findCatalogGearWithScore(gearNameOrId, category);

  const candidates: { realId?: string; score: number; type: "verified" | "manifest" | "catalog" }[] = [];

  if (verifiedMatch) {
    candidates.push({ realId: verifiedMatch.gear.realId, score: verifiedMatch.score, type: "verified" });
  }
  if (manifestMatch) {
    candidates.push({ realId: manifestMatch.gear.realId, score: manifestMatch.score, type: "manifest" });
  }
  if (catalogMatch) {
    candidates.push({ realId: catalogMatch.gear.guid, score: catalogMatch.score, type: "catalog" });
  }

  if (candidates.length === 0) return undefined;

  const getScoringTier = (score: number) => {
    if (score >= 1000) return 3; // EXACT MATCH
    if (score >= 150) return 2;  // STRONG MATCH
    return 1;                    // WEAK/TOKEN MATCH
  };

  candidates.sort((a, b) => {
    const aTier = getScoringTier(a.score);
    const bTier = getScoringTier(b.score);

    if (bTier !== aTier) {
      return bTier - aTier;
    }

    const aBonus = a.type === "verified" ? 5000 : a.type === "catalog" ? 1000 : 0;
    const bBonus = b.type === "verified" ? 5000 : b.type === "catalog" ? 1000 : 0;
    const aScore = a.score + aBonus;
    const bScore = b.score + bBonus;

    if (bScore !== aScore) {
      return bScore - aScore;
    }
    const aHasId = !!(a.realId && a.realId.trim() !== "");
    const bHasId = !!(b.realId && b.realId.trim() !== "");
    if (aHasId !== bHasId) {
      return bHasId ? 1 : -1;
    }
    return 0;
  });

  const best = candidates[0];
  if (best.score < 150) {
    return undefined;
  }
  return best.realId;
}

export function inferParameterKind(
  friendlyName: string,
  xmlName?: string
): "continuous_knob" | "switch_boolean" | "enum" | "frequency" | "gain_db" | "time_ms" | "semantic" | undefined {
  const name = friendlyName.toLowerCase().trim();
  const xml = xmlName ? xmlName.toLowerCase().trim() : "";
  
  const knownKnobs = ["drive", "gain", "lead drive", "master", "volume", "treble", "bass", "middle", "mid", "presence", "reverb"];
  const knownSwitches = ["bright", "shift", "rhythm2", "deep", "eq on/off", "eq", "eq_"];

  if (knownKnobs.some(k => name.includes(k) || xml.includes(k))) {
    return "continuous_knob";
  }
  if (knownSwitches.some(s => name.includes(s) || xml.includes(s))) {
    return "switch_boolean";
  }
  return undefined;
}

export const resolveGearParameters = getParameterDefinitions;

export function getParameterDefinitions(
  gearNameOrId: string | undefined,
  category?: string
): ResolvedParameter[] {
  if (!gearNameOrId) return [];

  const verifiedMatch = findVerifiedGearWithScore(gearNameOrId, category);
  const manifestMatch = findManifestGearWithScore(gearNameOrId, category);
  const catalogMatch = findCatalogGearWithScore(gearNameOrId, category);

  const candidates: { type: "verified" | "manifest" | "catalog"; score: number; data: any }[] = [];

  if (verifiedMatch) {
    candidates.push({ type: "verified", score: verifiedMatch.score, data: verifiedMatch.gear });
  }
  if (manifestMatch) {
    candidates.push({ type: "manifest", score: manifestMatch.score, data: manifestMatch.gear });
  }
  if (catalogMatch) {
    candidates.push({ type: "catalog", score: catalogMatch.score, data: catalogMatch.gear });
  }

  const getScoringTier = (score: number) => {
    if (score >= 1000) return 3; // EXACT MATCH
    if (score >= 150) return 2;  // STRONG MATCH
    return 1;                    // WEAK/TOKEN MATCH
  };

  candidates.sort((a, b) => {
    const aTier = getScoringTier(a.score);
    const bTier = getScoringTier(b.score);

    if (bTier !== aTier) {
      return bTier - aTier;
    }

    const aBonus = a.type === "verified" ? 5000 : a.type === "catalog" ? 1000 : 0;
    const bBonus = b.type === "verified" ? 5000 : b.type === "catalog" ? 1000 : 0;
    return (b.score + bBonus) - (a.score + aBonus);
  });

  const best = candidates.length > 0 ? candidates[0] : undefined;

  let baseParams: ResolvedParameter[] = [];

  if (best) {
    if (best.type === "verified") {
      baseParams = best.data.params.map((p: any) => ({
        ...p,
        definitionSource: "verified_override" as const,
        authoritativeRange: [p.min, p.max] as [number, number],
      }));
    } else if (best.type === "catalog") {
      const gear = best.data;
      if (gear.knobs) {
        baseParams = gear.knobs.map((knob: any) => {
          const baseXmlName = compact(knob.name);
          const isExplicit = knob.max !== undefined;
          return {
            friendlyName: knob.name,
            xmlName: gear.group === "amp" && gear.paramSuffix ? `${baseXmlName}${gear.paramSuffix}` : baseXmlName,
            min: knob.min ?? 0,
            max: knob.max ?? 10,
            defaultValue: knob.default !== undefined ? knob.default : undefined,
            definitionSource: isExplicit ? ("catalog_explicit" as const) : ("catalog_fallback" as const),
            authoritativeRange: isExplicit ? ([knob.min ?? 0, knob.max] as [number, number]) : undefined,
          };
        });
      }
    } else {
      const gear = best.data;
      if (gear.knobs) {
        baseParams = gear.knobs.filter(isKnobDefinition).map((knob: any) => {
          const baseXmlName = compact(knob.name);
          const isExplicit = knob.max !== undefined;
          return {
            friendlyName: knob.name,
            xmlName: gear.category === "amp" && gear.paramSuffix ? `${baseXmlName}${gear.paramSuffix}` : baseXmlName,
            min: knob.min ?? 0,
            max: knob.max ?? 10,
            unit: knob.unit,
            definitionSource: isExplicit ? ("catalog_explicit" as const) : ("catalog_fallback" as const),
            authoritativeRange: isExplicit ? ([knob.min ?? 0, knob.max] as [number, number]) : undefined,
          };
        });
      }
    }
  }

  // Merge dynamic database mapping overrides to resolve discrepancies and keep the Exporter matched to the Profile Management source of truth
  let displayName = "";
  let aliases: string[] = [];
  let bestGuid = "";
  if (best) {
    if (best.type === "verified") {
      displayName = best.data.name;
      aliases = best.data.aliases ?? [];
      bestGuid = best.data.realId ?? "";
    } else if (best.type === "catalog") {
      displayName = best.data.displayName;
      aliases = [
        ...(best.data.otherNames || []),
        ...(best.data.examplePresets || [])
      ];
      bestGuid = best.data.guid ?? "";
    } else {
      displayName = best.data.name;
      aliases = [];
      bestGuid = best.data.realId ?? "";
    }
  } else {
    displayName = gearNameOrId;
    aliases = [];
  }

  const aliasSet = new Set([
    normalise(gearNameOrId),
    cleanGearNameForMatching(gearNameOrId),
    normalise(displayName),
    cleanGearNameForMatching(displayName),
    ...aliases.map(a => normalise(a)),
    ...aliases.map(a => cleanGearNameForMatching(a))
  ]);

  const rawCleanGuid = (bestGuid || gearNameOrId).toLowerCase().replace(/[^a-z0-9]/g, '');

  let relevantDb = dbParameterMappings.filter(m => {
    if (aliasSet.has(normalise(m.gearName))) return true;
    if (aliasSet.has(cleanGearNameForMatching(m.gearName))) return true;
    if (m.gearGuid) {
      const mGuid = m.gearGuid.toLowerCase().replace(/[^a-z0-9]/g, '');
      if (mGuid && (mGuid === rawCleanGuid || (bestGuid && mGuid === bestGuid.toLowerCase().replace(/[^a-z0-9]/g, '')))) {
        return true;
      }
    }
    return false;
  });

  if (best && best.type === "verified" && displayName === "Jazz Amp 120") {
    relevantDb = relevantDb.filter(m => {
      const xml = m.exportParameterName || "";
      return !xml.endsWith("_Roland120") && !xml.includes("Roland120");
    });
  }

  if (!best && relevantDb.length === 0) {
    return [];
  }

  const paramsMap = new Map<string, ResolvedParameter>();
  for (const p of baseParams) {
    if (!p.kind) {
      p.kind = inferParameterKind(p.friendlyName, p.xmlName);
    }
    paramsMap.set(p.friendlyName.toLowerCase().trim(), p);
  }

  for (const dbM of relevantDb) {
    const targetKeys = [
      dbM.parameter,
      dbM.exportParameterName,
      dbM.canonicalParameterName,
      dbM.displayParameterName
    ].filter(Boolean).map(s => s!.toLowerCase().trim());

    let existing: ResolvedParameter | undefined = undefined;
    for (const k of targetKeys) {
      if (paramsMap.has(k)) {
        existing = paramsMap.get(k);
        break;
      }
    }

    if (!existing) {
      for (const p of paramsMap.values()) {
        const namesToCompare = [
          p.friendlyName,
          p.xmlName,
          ...(p.aliases || []),
          ...(p.effectiveAliases || [])
        ].filter(Boolean).map(s => s.toLowerCase().trim());

        if (targetKeys.some(tk => namesToCompare.includes(tk))) {
          existing = p;
          break;
        }
      }
    }

    if (existing) {
      existing.friendlyName = dbM.displayParameterName || dbM.parameter || existing.friendlyName;
      existing.displayParameterName = dbM.displayParameterName || dbM.parameter || existing.friendlyName;
      existing.canonicalParameterName = dbM.canonicalParameterName || dbM.exportParameterName || existing.xmlName;
      existing.xmlName = dbM.exportParameterName || existing.xmlName;
      
      const isKnownContinuousAmpKnob = existing.kind === "continuous_knob" || 
        (existing.max > 1 && inferParameterKind(existing.friendlyName, existing.xmlName) === "continuous_knob");
      
      const dbWantsToDowngrade = dbM.exportMax === 1;
      const dbIsSwitch = dbM.conversion === "boolean" || dbM.conversion === "enum";
      
      if (isKnownContinuousAmpKnob && dbWantsToDowngrade && !dbIsSwitch) {
        // Prevent downgrading a known continuous amp knob from 0-10 to 0-1
        // Keep existing.min and existing.max as they are
      } else {
        // Diagnostic Protection: Warn if authoritative DB mapping resolves a conflicting range over lower-priority source
        if (existing.definitionSource && existing.definitionSource !== "db_mapping") {
          if (existing.min !== dbM.exportMin || existing.max !== dbM.exportMax) {
            console.warn(
              `[AT5 Parameter Resolution Priority] Authoritative range [${dbM.exportMin}, ${dbM.exportMax}] from DB mapping (${dbM.source || 'db_mapping'}) applied over lower-priority [${existing.min}, ${existing.max}] from ${existing.definitionSource} for gear "${displayName}" (GUID: ${dbM.gearGuid || bestGuid || 'none'}), parameter "${dbM.parameter}".`
            );
          }
        }
        existing.min = dbM.exportMin;
        existing.max = dbM.exportMax;
        existing.definitionSource = "db_mapping";
        existing.authoritativeRange = [dbM.exportMin, dbM.exportMax];
      }
      
      existing.transform = dbM.conversion as any;
      existing.visualMin = dbM.visualMin;
      existing.visualMax = dbM.visualMax;

      const dbCombinedAliases = Array.from(new Set([
        ...(dbM.aliases || []),
        ...(dbM.savedAliases || []),
        ...(dbM.effectiveAliases || [])
      ].filter(Boolean)));

      if (dbCombinedAliases.length > 0) {
        existing.savedAliases = Array.from(new Set([...(existing.savedAliases || []), ...dbCombinedAliases]));
        existing.rawMappingAliases = Array.from(new Set([...(existing.rawMappingAliases || []), ...dbCombinedAliases]));
        existing.aliases = Array.from(new Set([...(existing.aliases || []), ...dbCombinedAliases]));
        existing.effectiveAliases = Array.from(new Set([
          ...(existing.effectiveAliases || []),
          ...(existing.aliases || []),
          ...(existing.savedAliases || []),
          ...(existing.rawMappingAliases || []),
          existing.friendlyName,
          existing.xmlName
        ].filter(Boolean)));
      }

      // Propagate extended fields
      existing.gearGuid = dbM.gearGuid || existing.gearGuid;
      existing.displayParameterName = dbM.displayParameterName || existing.displayParameterName || existing.friendlyName;
      existing.canonicalParameterName = dbM.canonicalParameterName || existing.canonicalParameterName || existing.xmlName;
      existing.at5XmlAttributeName = dbM.at5XmlAttributeName || existing.at5XmlAttributeName || existing.xmlName;
      existing.interfaceType = dbM.interfaceType ?? existing.interfaceType;
      existing.parameterKind = dbM.parameterKind ?? existing.parameterKind;
      existing.displayMin = dbM.displayMin ?? existing.displayMin;
      existing.displayMax = dbM.displayMax ?? existing.displayMax;
      existing.displayUnit = dbM.displayUnit ?? existing.displayUnit;
      existing.displayStep = dbM.displayStep ?? existing.displayStep;
      existing.decimalPlaces = dbM.decimalPlaces ?? existing.decimalPlaces;
      existing.displayPrecision = dbM.displayPrecision ?? existing.displayPrecision;
      existing.displayDecimalPlaces = dbM.displayDecimalPlaces ?? existing.displayDecimalPlaces;
      existing.defaultDisplayValue = dbM.defaultDisplayValue ?? existing.defaultDisplayValue;
      existing.exportUnit = dbM.exportUnit ?? existing.exportUnit;
      existing.exportStep = dbM.exportStep ?? existing.exportStep;
      existing.exportDecimalPlaces = dbM.exportDecimalPlaces ?? existing.exportDecimalPlaces;
      existing.exportPrecision = dbM.exportPrecision ?? existing.exportPrecision;
      existing.defaultExportValue = dbM.defaultExportValue ?? existing.defaultExportValue;
      existing.translationMode = dbM.translationMode ?? existing.translationMode;
      existing.valueMap = dbM.valueMap ?? existing.valueMap;
      existing.reverseValueMap = dbM.reverseValueMap ?? existing.reverseValueMap;
      existing.helperDescription = dbM.helperDescription ?? existing.helperDescription;
      existing.exampleInput = dbM.exampleInput ?? existing.exampleInput;
      existing.exampleOutput = dbM.exampleOutput ?? existing.exampleOutput;
      existing.mappingConfidence = dbM.mappingConfidence ?? existing.mappingConfidence;
      existing.source = dbM.source ?? existing.source;
      existing.doNotRequestForGear = dbM.doNotRequestForGear ?? existing.doNotRequestForGear;
      existing.unsupportedReason = dbM.unsupportedReason ?? existing.unsupportedReason;
      existing.reviewNotes = dbM.reviewNotes ?? existing.reviewNotes;
      existing.optionRows = dbM.optionRows ?? existing.optionRows;
      existing.valueMapJson = dbM.valueMapJson ?? existing.valueMapJson;
      existing.reverseValueMapJson = dbM.reverseValueMapJson ?? existing.reverseValueMapJson;
    } else {
      const inferredKind = inferParameterKind(dbM.parameter, dbM.exportParameterName);
      const isKnownContinuousAmpKnob = inferredKind === "continuous_knob";
      
      let finalMin = dbM.exportMin;
      let finalMax = dbM.exportMax;
      
      if (isKnownContinuousAmpKnob && dbM.exportMax === 1 && dbM.conversion !== "boolean" && dbM.conversion !== "enum") {
        finalMin = 0;
        finalMax = 10;
      }
      
      const dbCombinedAliases = Array.from(new Set([
        ...(dbM.aliases || []),
        ...(dbM.savedAliases || []),
        ...(dbM.effectiveAliases || [])
      ].filter(Boolean)));
      const newDisplayName = dbM.displayParameterName || dbM.parameter;
      const newCanonicalName = dbM.canonicalParameterName || dbM.exportParameterName;
      const newKey = (newCanonicalName || newDisplayName).toLowerCase().trim();

      paramsMap.set(newKey, {
        friendlyName: newDisplayName,
        xmlName: newCanonicalName,
        min: finalMin,
        max: finalMax,
        transform: dbM.conversion as any,
        aliases: dbCombinedAliases,
        savedAliases: dbCombinedAliases,
        rawMappingAliases: dbCombinedAliases,
        effectiveAliases: Array.from(new Set([
          ...dbCombinedAliases,
          newDisplayName,
          newCanonicalName
        ].filter(Boolean))),
        visualMin: dbM.visualMin,
        visualMax: dbM.visualMax,
        kind: inferredKind,
        definitionSource: "db_mapping",
        authoritativeRange: [finalMin, finalMax],

        // Propagate extended fields
        gearGuid: dbM.gearGuid,
        displayParameterName: dbM.displayParameterName || newDisplayName,
        canonicalParameterName: dbM.canonicalParameterName || newCanonicalName,
        at5XmlAttributeName: dbM.at5XmlAttributeName || newCanonicalName,
        interfaceType: dbM.interfaceType,
        parameterKind: dbM.parameterKind,
        displayMin: dbM.displayMin,
        displayMax: dbM.displayMax,
        displayUnit: dbM.displayUnit,
        displayStep: dbM.displayStep,
        decimalPlaces: dbM.decimalPlaces,
        displayPrecision: dbM.displayPrecision,
        displayDecimalPlaces: dbM.displayDecimalPlaces,
        defaultDisplayValue: dbM.defaultDisplayValue,
        exportUnit: dbM.exportUnit,
        exportStep: dbM.exportStep,
        exportDecimalPlaces: dbM.exportDecimalPlaces,
        exportPrecision: dbM.exportPrecision,
        defaultExportValue: dbM.defaultExportValue,
        translationMode: dbM.translationMode,
        valueMap: dbM.valueMap,
        reverseValueMap: dbM.reverseValueMap,
        helperDescription: dbM.helperDescription,
        exampleInput: dbM.exampleInput,
        exampleOutput: dbM.exampleOutput,
        mappingConfidence: dbM.mappingConfidence,
        source: dbM.source,
        doNotRequestForGear: dbM.doNotRequestForGear,
        unsupportedReason: dbM.unsupportedReason,
        reviewNotes: dbM.reviewNotes,
        optionRows: dbM.optionRows,
        valueMapJson: dbM.valueMapJson,
        reverseValueMapJson: dbM.reverseValueMapJson
      });
    }
  }

  // Enrich aliases for all resolved parameters dynamically using generateAliasesForXmlParam
  for (const p of paramsMap.values()) {
    if (!p.aliases) {
      p.aliases = [];
    }
    if (!p.savedAliases) {
      p.savedAliases = [...p.aliases];
    }
    if (!p.rawMappingAliases) {
      p.rawMappingAliases = [...p.aliases];
    }
    
    const generatedFromXml = generateAliasesForXmlParam(p.xmlName);
    const generatedFromFriendly = generateAliasesForXmlParam(p.friendlyName);
    const autoGen = Array.from(new Set([...generatedFromXml, ...generatedFromFriendly]));
    p.autoGeneratedAliases = autoGen;

    const seenClean = new Set<string>();
    const effective: string[] = [];

    const addEffective = (aliasStr: string) => {
      if (!aliasStr) return;
      const clean = aliasStr.toLowerCase().replace(/[^a-z0-9.]/g, "").trim();
      if (clean && !seenClean.has(clean)) {
        seenClean.add(clean);
        effective.push(aliasStr);
      }
    };

    addEffective(p.friendlyName);
    addEffective(p.xmlName);
    if (p.canonicalParameterName) addEffective(p.canonicalParameterName);
    if (p.displayParameterName) addEffective(p.displayParameterName);
    (p.savedAliases || []).forEach(addEffective);
    (p.rawMappingAliases || []).forEach(addEffective);
    autoGen.forEach(addEffective);

    p.effectiveAliases = effective;
    p.aliases = effective;
  }

  // Ensure parameters are strictly deduplicated by unique object reference and canonical identity
  const uniqueParams: VerifiedParamDef[] = [];
  const seenRefs = new Set<VerifiedParamDef>();
  const seenIdentities = new Set<string>();

  for (const p of paramsMap.values()) {
    if (seenRefs.has(p)) continue;
    seenRefs.add(p);

    const identity = (p.xmlName || p.canonicalParameterName || p.displayParameterName || p.friendlyName || '').toLowerCase().trim();
    if (identity && seenIdentities.has(identity)) continue;
    if (identity) seenIdentities.add(identity);

    uniqueParams.push(p);
  }

  return uniqueParams;
}

export const parseSettingValue = (
  value: unknown,
  transform?: VerifiedParamDef["transform"] | string,
  min?: number,
  max?: number,
  visualMin?: number,
  visualMax?: number,
  def?: any
): string | number | undefined => {
  if (value === undefined || value === null) return undefined;
  
  const valStr = String(value).trim();
  const valStrLower = valStr.toLowerCase();

  // Prioritized option rows, valueMap, and JSON parsing
  if (def) {
    // 1. optionRows
    if (def.optionRows && Array.isArray(def.optionRows) && def.optionRows.length > 0) {
      const matched = def.optionRows.find((row: any) => {
        if (row.displayLabel && row.displayLabel.trim().toLowerCase() === valStrLower) return true;
        if (row.aliases && Array.isArray(row.aliases)) {
          if (row.aliases.some((alias: string) => alias && alias.trim().toLowerCase() === valStrLower)) return true;
        }
        if (row.exportValue !== undefined && String(row.exportValue).trim().toLowerCase() === valStrLower) return true;
        return false;
      });
      if (matched !== undefined) {
        const ev = matched.exportValue;
        if (typeof ev === "number") return ev;
        const num = parseFloat(ev);
        return isNaN(num) ? ev : num;
      }
    }

    // 2. valueMap object
    if (def.valueMap && typeof def.valueMap === 'object') {
      const keys = Object.keys(def.valueMap);
      const matchedKey = keys.find(k => k.trim().toLowerCase() === valStrLower);
      if (matchedKey !== undefined) {
        const ev = def.valueMap[matchedKey];
        if (typeof ev === "number") return ev;
        const num = parseFloat(String(ev));
        return isNaN(num) ? ev : num;
      }
    }

    // 3. parsed Value Map JSON
    if (def.valueMapJson && typeof def.valueMapJson === 'string') {
      try {
        const parsed = JSON.parse(def.valueMapJson);
        if (parsed && typeof parsed === 'object') {
          const keys = Object.keys(parsed);
          const matchedKey = keys.find(k => k.trim().toLowerCase() === valStrLower);
          if (matchedKey !== undefined) {
            const ev = parsed[matchedKey];
            if (typeof ev === "number") return ev;
            const num = parseFloat(String(ev));
            return isNaN(num) ? ev : num;
          }
        }
      } catch (e) {
        // Ignore
      }
    }
  }
  
  const text = valStrLower;
  if (text === "" || text === "undefined" || text === "null") return undefined;
  
  if (transform === "vibratoChorusJC120") {
    if (text === "off" || text === "0") return 0;
    if (text === "chorus" || text === "chr" || text === "1") return 1;
    if (text === "vibrato" || text === "vib" || text === "2") return 2;
    const num = parseFloat(text);
    if (!isNaN(num)) return Math.min(2, Math.max(0, num));
    return 0;
  }

  if (transform === "black76Ratio") {
    if (text.includes("20")) return "_20";
    if (text.includes("12")) return "_12";
    if (text.includes("8")) return "_8";
    if (text.includes("4")) return "_4";
    if (text.includes("all")) return "All";
    
    const num = parseFloat(text);
    if (num === 20) return "_20";
    if (num === 12) return "_12";
    if (num === 8) return "_8";
    if (num === 4) return "_4";
    
    return "_4";
  }

  if (typeof value === "number") return value;

  let n: number | undefined;

  // Compressor Ratio mapping (Generic fallback - legacy)
  if (text.includes("ratio") && !transform) {
    if (text.includes("4:1") || text === "4" || text === "_4") n = 0;
    else if (text.includes("8:1") || text === "8" || text === "_8") n = 1;
    else if (text.includes("12:1") || text === "12" || text === "_12") n = 2;
    else if (text.includes("20:1") || text === "20" || text === "_20") n = 3;
    else if (text.includes("all")) n = 4;
  }

  if (n === undefined) {
    const first = text.match(/-?\d+(?:\.\d+)?(?:e-?\d+)?/i)?.[0];
    if (!first) {
      // If no numeric data found, but it's a non-empty alphanumeric string,
      // treat it as a potential enum value (e.g. "Low", "All").
      if (text.length > 0 && /^[a-z0-9_\s]+$/i.test(text)) {
        return String(value).trim();
      }
      return undefined;
    }
    n = parseFloat(first);
  }
  if (!Number.isFinite(n)) return undefined;

  if (transform === "db_to_linear") {
    // Determine effective display dB range
    let dMin = def?.displayMin ?? def?.visual?.min ?? visualMin;
    let dMax = def?.displayMax ?? def?.visual?.max ?? visualMax;
    const expMin = def?.exportMin ?? def?.export?.min ?? min ?? 0.177828;
    const expMax = def?.exportMax ?? def?.export?.max ?? max ?? 5.62341;

    // Check if visual range is corrupted (equals export range) or missing
    if (dMin === undefined || dMax === undefined || (dMin === expMin && dMax === expMax) || (dMin >= 0 && dMax > 1 && dMax <= 10)) {
      if (def?.displayMin !== undefined && def?.displayMax !== undefined && (def.displayMin !== expMin || def.displayMax !== expMax)) {
        dMin = def.displayMin;
        dMax = def.displayMax;
      } else {
        dMin = -15;
        dMax = 15;
      }
    }

    const actualDMin = Math.min(dMin, dMax);
    const actualDMax = Math.max(dMin, dMax);

    // 1. Clamp display dB value against display range
    const clampedDb = Math.min(actualDMax, Math.max(actualDMin, n));
    // 2. Convert display dB to linear raw value
    n = Math.pow(10, clampedDb / 20);
  } else if (transform === "dbThresholdToLinear") {
    const db = Math.min(0, Math.max(-100, n));
    n = Math.pow(10, db / 20);
  }

  if (transform === "linear_to_db") {
    if (n <= 0) {
      n = -100;
    } else {
      n = 20 * Math.log10(n);
    }
  }

  if (transform === "scaled_range") {
    const vMin = visualMin ?? 0;
    const vMax = visualMax ?? 10;
    const expMin = min ?? 0;
    const expMax = max ?? 10;
    const pct = (vMin === vMax) ? 0 : (n - vMin) / (vMax - vMin);
    n = expMin + pct * (expMax - expMin);
  }

  if (transform === "khzToHzIfNeeded") {
    if (text.includes("khz")) n *= 1000;
  }

  if (transform === "noiseGateRelease") {
    if (text.includes("ms")) {
      // already milliseconds
    } else if (text.includes("s") || text.includes("sec")) {
      n = n * 1000;
    } else if (n > 1.5 && n <= 10) {
      n = 20 + n * 148; // treat as 20-1500 dial (0-10 scale)
    } else if (n <= 1.5) {
      n = n * 1000; // treat as seconds (e.g. 1.2 -> 1200ms)
    }
  }

  if (transform === "noiseGateDepth") {
    // If input is 0..10 and not explicitly dB, convert to AT5 dB range: -100..-20
    if (!text.includes("db") && n >= 0 && n <= 10) {
      // 0 -> -100, 10 -> -20. Linear mapping: -100 + (n * 8)
      n = -100 + n * 8;
    }
  }

  if (transform === "black76InputOutput") {
    // Treat values as dB if they include dB or are numeric.
    // UI range is -99.0 dB to 0.0 dB.
    // Convert to linear: linear = Math.pow(10, db / 20)
    
    let db = n;
    if (db > 0) db = 0; // Clamp positive to 0 dB
    if (db < -99) db = -99; // Clamp lower bound
    
    n = Math.pow(10, db / 20);
  }

  return n;
};

export interface ConvertParameterOptions {
  inputValue: unknown;
  parameterDef?: any;
  conversionMode?: string;
  displayMin?: number;
  displayMax?: number;
  exportMin?: number;
  exportMax?: number;
  displayUnit?: string;
  displayPrecision?: number;
  displayDecimalPlaces?: number;
  exportDecimalPlaces?: number;
  exportPrecision?: number;
}

export interface ConvertParameterResult {
  inputValue: unknown;
  inputDisplayValue: number | string;
  parsedNumericValue?: number;
  conversionMode: string;
  displayUnit: string;
  displayMin: number;
  displayMax: number;
  displayClampApplied: boolean;
  clampedDisplayValue: number | string;
  convertedRawValue: number;
  exportMin: number;
  exportMax: number;
  rawClampApplied: boolean;
  clampApplied: boolean;
  finalExportValue: number;
  formattedExportValue: string;
  reverseDisplayValue: string;
  displayPrecision: number;
  exportPrecision?: number;
  formattedVisualMin: string;
  formattedVisualMax: string;
  formattedExportMin: string;
  formattedExportMax: string;
  warnings: string[];
}

export function convertParameterValueForExport(options: ConvertParameterOptions): ConvertParameterResult {
  const { inputValue, parameterDef } = options;
  const warnings: string[] = [];

  let mode = (options.conversionMode || parameterDef?.transform || parameterDef?.conversion?.mode || parameterDef?.translationMode || parameterDef?.conversion || "direct") as string;
  if (mode === "gain_db") mode = "db_to_linear";

  let val = inputValue;
  if (val === undefined || val === null || val === "") {
    val = parameterDef?.defaultValue ?? parameterDef?.defaultDisplayValue ?? 0;
  }

  const valStr = String(val).trim();
  const valStrLower = valStr.toLowerCase();

  // Option rows & valueMap handling for enums/switches
  if (parameterDef) {
    if (parameterDef.optionRows && Array.isArray(parameterDef.optionRows)) {
      const match = parameterDef.optionRows.find((r: any) =>
        String(r.displayLabel).trim().toLowerCase() === valStrLower ||
        String(r.canonicalValue).trim().toLowerCase() === valStrLower
      );
      if (match && match.exportValue !== undefined) {
        val = match.exportValue;
      }
    } else if (parameterDef.valueMap && typeof parameterDef.valueMap === "object") {
      const keys = Object.keys(parameterDef.valueMap);
      const matchKey = keys.find(k => k.trim().toLowerCase() === valStrLower);
      if (matchKey !== undefined) {
        val = parameterDef.valueMap[matchKey];
      }
    }
  }

  // Unit
  let rawUnit = options.displayUnit ?? parameterDef?.displayUnit ?? parameterDef?.unit ?? "";
  if (rawUnit.toLowerCase() === "linear" && (mode === "db_to_linear" || mode === "dbThresholdToLinear")) {
    rawUnit = "dB";
  }
  const unit = rawUnit || (
    mode === "db_to_linear" || mode === "dbThresholdToLinear" || mode === "noiseGateDepth" || mode === "linear_to_db" ? "dB" : ""
  );

  // Decimal places for export and display formatting
  const isLinearFloatMode = mode === "db_to_linear" || mode === "dbThresholdToLinear" || mode === "black76InputOutput" || mode === "linear_to_db";

  // Export Range
  const authoritativeMin = parameterDef?.authoritativeRange?.[0];
  const authoritativeMax = parameterDef?.authoritativeRange?.[1];

  let expMin: number;
  let expMax: number;

  if (authoritativeMin !== undefined && authoritativeMax !== undefined && (parameterDef?.definitionSource === "db_mapping" || parameterDef?.definitionSource === "verified_override")) {
    expMin = authoritativeMin;
    expMax = authoritativeMax;
    if (options.exportMin !== undefined && options.exportMax !== undefined && (options.exportMin !== expMin || options.exportMax !== expMax)) {
      console.warn(
        `[AT5 Exporter Resolution Priority] Authoritative range [${expMin}, ${expMax}] from ${parameterDef.definitionSource} takes precedence over options bounds [${options.exportMin}, ${options.exportMax}] for parameter "${parameterDef.friendlyName || parameterDef.xmlName}".`
      );
    }
  } else {
    expMin = options.exportMin ?? parameterDef?.exportMin ?? parameterDef?.export?.min ?? parameterDef?.min ?? (mode === "db_to_linear" ? 0.177828 : 0);
    expMax = options.exportMax ?? parameterDef?.exportMax ?? parameterDef?.export?.max ?? parameterDef?.max ?? (mode === "db_to_linear" ? 5.62341 : 1);
  }

  const actualExpMin = Math.min(expMin, expMax);
  const actualExpMax = Math.max(expMin, expMax);

  const isSubOneExportRange = actualExpMax <= 1.05 && mode !== "boolean" && mode !== "enum";

  // Precision resolution: Display precision vs Export precision
  const rawDispPrec = options.displayPrecision ?? options.displayDecimalPlaces ?? parameterDef?.displayPrecision ?? parameterDef?.displayDecimalPlaces ?? parameterDef?.decimalPlaces;
  const isDiscrete = mode === "boolean" || mode === "enum" || parameterDef?.parameterKind === "boolean" || parameterDef?.parameterKind === "enum" || parameterDef?.parameterKind === "selector";
  const dispPrecision: number = rawDispPrec !== undefined && rawDispPrec !== null ? Math.max(0, Math.round(Number(rawDispPrec))) : (isDiscrete ? 0 : 2);

  const rawExpPrec = options.exportPrecision ?? options.exportDecimalPlaces ?? parameterDef?.exportPrecision ?? parameterDef?.exportDecimalPlaces;
  const explicitExpPrecision = rawExpPrec !== undefined && rawExpPrec !== null ? Math.max(0, Math.round(Number(rawExpPrec))) : undefined;

  let decPlaces: number;
  if (explicitExpPrecision !== undefined) {
    decPlaces = explicitExpPrecision;
  } else if (isLinearFloatMode || isSubOneExportRange) {
    // Float modes and small linear export ranges require 6 decimal places to prevent truncation to 0
    decPlaces = 6;
  } else if (parameterDef?.decimalPlaces !== undefined) {
    decPlaces = Math.max(0, Math.round(Number(parameterDef.decimalPlaces)));
  } else {
    decPlaces = 6;
  }

  if (isLinearFloatMode && decPlaces < 6 && explicitExpPrecision === undefined) {
    decPlaces = 6;
  }

  // Display Range
  let dMin = options.displayMin ?? parameterDef?.displayMin ?? parameterDef?.visualMin ?? parameterDef?.visual?.min;
  let dMax = options.displayMax ?? parameterDef?.displayMax ?? parameterDef?.visualMax ?? parameterDef?.visual?.max;

  if (mode === "db_to_linear") {
    if (dMin === undefined || dMax === undefined || (dMin === expMin && dMax === expMax) || (dMin >= 0 && dMax > 1 && dMax <= 10)) {
      if (parameterDef?.displayMin !== undefined && parameterDef?.displayMax !== undefined && (parameterDef.displayMin !== expMin || parameterDef.displayMax !== expMax)) {
        dMin = parameterDef.displayMin;
        dMax = parameterDef.displayMax;
      } else {
        dMin = -15;
        dMax = 15;
      }
    }
  } else if (mode === "dbThresholdToLinear") {
    dMin = -100;
    dMax = 0;
  } else {
    if (dMin === undefined) dMin = 0;
    if (dMax === undefined) dMax = (mode === "scaled_range" ? 10 : expMax);
  }

  const displayMin = Math.min(dMin, dMax);
  const displayMax = Math.max(dMin, dMax);

  // Parse numeric
  let numVal: number | undefined;
  if (typeof val === "number") {
    numVal = val;
  } else {
    const match = valStr.match(/-?\d+(?:\.\d+)?(?:e-?\d+)?/i);
    if (match) {
      numVal = parseFloat(match[0]);
    }
  }

  const formattedVisualMin = displayMin.toFixed(dispPrecision);
  const formattedVisualMax = displayMax.toFixed(dispPrecision);
  const formattedExportMin = explicitExpPrecision !== undefined ? actualExpMin.toFixed(explicitExpPrecision) : (isLinearFloatMode ? actualExpMin.toFixed(6) : String(actualExpMin));
  const formattedExportMax = explicitExpPrecision !== undefined ? actualExpMax.toFixed(explicitExpPrecision) : (isLinearFloatMode ? actualExpMax.toFixed(6) : String(actualExpMax));

  // Non-numeric fallback (e.g. enum strings "Low", "All")
  if (numVal === undefined || !Number.isFinite(numVal)) {
    return {
      inputValue,
      inputDisplayValue: valStr,
      conversionMode: mode,
      displayUnit: unit,
      displayMin,
      displayMax,
      displayClampApplied: false,
      clampedDisplayValue: valStr,
      convertedRawValue: 0,
      exportMin: actualExpMin,
      exportMax: actualExpMax,
      rawClampApplied: false,
      clampApplied: false,
      finalExportValue: 0,
      formattedExportValue: valStr,
      reverseDisplayValue: valStr,
      displayPrecision: dispPrecision,
      exportPrecision: explicitExpPrecision,
      formattedVisualMin,
      formattedVisualMax,
      formattedExportMin,
      formattedExportMax,
      warnings: []
    };
  }

  const inputDisplayVal = numVal;
  let clampedDisplayVal = numVal;
  let displayClampApplied = false;
  let rawVal = numVal;
  let clampedRawVal = numVal;
  let rawClampApplied = false;

  if (mode === "db_to_linear") {
    // 1. Clamp display dB value to display range
    if (numVal < displayMin || numVal > displayMax) {
      clampedDisplayVal = Math.min(displayMax, Math.max(displayMin, numVal));
      displayClampApplied = true;
      warnings.push(`Input display value was clamped from ${numVal} dB to ${clampedDisplayVal} dB.`);
    } else {
      clampedDisplayVal = numVal;
    }
    // 2. Convert dB to raw linear value
    rawVal = Math.pow(10, clampedDisplayVal / 20);

    // 3. Clamp raw linear value to export range
    if (rawVal < actualExpMin || rawVal > actualExpMax) {
      clampedRawVal = Math.min(actualExpMax, Math.max(actualExpMin, rawVal));
      if (Math.abs(clampedRawVal - rawVal) > 1e-5) {
        rawClampApplied = true;
        warnings.push(`Converted raw linear value ${rawVal.toFixed(6)} was clamped to export bounds [${actualExpMin}, ${actualExpMax}].`);
      } else {
        clampedRawVal = rawVal;
      }
    } else {
      clampedRawVal = rawVal;
    }
  } else if (mode === "dbThresholdToLinear") {
    // Negative threshold control (-100 to 0 dB)
    if (numVal < -100 || numVal > 0) {
      clampedDisplayVal = Math.min(0, Math.max(-100, numVal));
      displayClampApplied = true;
      warnings.push(`Threshold dB value ${numVal >= 0 ? "+" + numVal : numVal} dB was clamped to threshold bounds [-100, 0] dB (${clampedDisplayVal} dB).`);
    } else {
      clampedDisplayVal = numVal;
    }
    rawVal = Math.pow(10, clampedDisplayVal / 20);
    if (rawVal < actualExpMin || rawVal > actualExpMax) {
      clampedRawVal = Math.min(actualExpMax, Math.max(actualExpMin, rawVal));
      if (Math.abs(clampedRawVal - rawVal) > 1e-5) {
        rawClampApplied = true;
        warnings.push(`Converted raw linear value ${rawVal.toFixed(6)} was clamped to export bounds [${actualExpMin}, ${actualExpMax}].`);
      } else {
        clampedRawVal = rawVal;
      }
    } else {
      clampedRawVal = rawVal;
    }
  } else if (mode === "linear_to_db") {
    const db = numVal <= 0 ? -100 : 20 * Math.log10(numVal);
    rawVal = Math.min(actualExpMax, Math.max(actualExpMin, db));
    clampedRawVal = rawVal;
  } else if (mode === "scaled_range") {
    const span = displayMax - displayMin;
    const pct = span === 0 ? 0 : (numVal - displayMin) / span;
    const clampedPct = Math.min(1, Math.max(0, pct));
    if (clampedPct !== pct) {
      displayClampApplied = true;
    }
    rawVal = actualExpMin + clampedPct * (actualExpMax - actualExpMin);
    clampedRawVal = Math.min(actualExpMax, Math.max(actualExpMin, rawVal));
  } else if (mode === "khzToHzIfNeeded") {
    let hz = numVal;
    if (valStrLower.includes("khz")) hz *= 1000;
    rawVal = Math.min(actualExpMax, Math.max(actualExpMin, hz));
    clampedRawVal = rawVal;
  } else if (mode === "noiseGateRelease") {
    let ms = numVal;
    if (valStrLower.includes("s") && !valStrLower.includes("ms")) ms *= 1000;
    else if (numVal > 1.5 && numVal <= 10) ms = 20 + numVal * 148;
    else if (numVal <= 1.5) ms *= 1000;
    rawVal = Math.min(actualExpMax, Math.max(actualExpMin, ms));
    clampedRawVal = rawVal;
  } else if (mode === "noiseGateDepth") {
    let depth = numVal;
    if (!valStrLower.includes("db") && numVal >= 0 && numVal <= 10) depth = -100 + numVal * 8;
    rawVal = Math.min(actualExpMax, Math.max(actualExpMin, depth));
    clampedRawVal = rawVal;
  } else if (mode === "black76InputOutput") {
    let db = numVal;
    if (db > 0) db = 0;
    if (db < -99) db = -99;
    rawVal = Math.pow(10, db / 20);
    clampedRawVal = Math.min(actualExpMax, Math.max(actualExpMin, rawVal));
  } else {
    // Direct
    if (numVal < actualExpMin || numVal > actualExpMax) {
      clampedRawVal = Math.min(actualExpMax, Math.max(actualExpMin, numVal));
      rawClampApplied = true;
      warnings.push(`Input value ${numVal} was clamped to export bounds [${actualExpMin}, ${actualExpMax}].`);
    } else {
      clampedRawVal = numVal;
    }
    rawVal = numVal;
  }

  const clampApplied = displayClampApplied || rawClampApplied;
  const finalVal = clampedRawVal;

  let formatted = "";
  if (explicitExpPrecision !== undefined) {
    formatted = finalVal.toFixed(explicitExpPrecision);
  } else if (Math.abs(finalVal - Math.round(finalVal)) < 1e-7 && !isLinearFloatMode && actualExpMin >= 1) {
    formatted = String(Math.round(finalVal));
  } else if (Math.abs(finalVal) < 1e-9 && (mode === "db_to_linear" || mode === "dbThresholdToLinear")) {
    formatted = "0";
  } else {
    const fixedStr = finalVal.toFixed(decPlaces);
    formatted = parseFloat(fixedStr).toString();
    if (formatted === "0" && Math.abs(finalVal) > 1e-7) {
      formatted = parseFloat(finalVal.toFixed(6)).toString();
    }
  }

  let reverseDisplay = "";
  if (mode === "db_to_linear" || mode === "dbThresholdToLinear") {
    const revDb = 20 * Math.log10(Math.max(1e-6, finalVal));
    const signStr = revDb >= 0 ? "+" : "";
    reverseDisplay = `${signStr}${revDb.toFixed(dispPrecision)} dB`;
  } else if (mode === "linear_to_db") {
    const revLin = Math.pow(10, finalVal / 20);
    reverseDisplay = revLin.toFixed(dispPrecision);
  } else if (mode === "scaled_range") {
    const span = actualExpMax - actualExpMin;
    const pct = span === 0 ? 0 : (finalVal - actualExpMin) / span;
    const revDisp = displayMin + pct * (displayMax - displayMin);
    reverseDisplay = `${revDisp.toFixed(dispPrecision)}${unit ? ' ' + unit : ''}`.trim();
  } else if (unit) {
    if (typeof clampedDisplayVal === "number") {
      reverseDisplay = `${clampedDisplayVal.toFixed(dispPrecision)} ${unit}`.trim();
    } else {
      reverseDisplay = `${clampedDisplayVal} ${unit}`.trim();
    }
  } else {
    if (typeof clampedDisplayVal === "number") {
      reverseDisplay = clampedDisplayVal.toFixed(dispPrecision);
    } else {
      reverseDisplay = String(clampedDisplayVal);
    }
  }

  return {
    inputValue,
    inputDisplayValue: inputDisplayVal,
    parsedNumericValue: numVal,
    conversionMode: mode,
    displayUnit: unit,
    displayMin,
    displayMax,
    displayClampApplied,
    clampedDisplayValue: clampedDisplayVal,
    convertedRawValue: rawVal,
    exportMin: actualExpMin,
    exportMax: actualExpMax,
    rawClampApplied,
    clampApplied,
    finalExportValue: finalVal,
    formattedExportValue: formatted,
    reverseDisplayValue: reverseDisplay,
    displayPrecision: dispPrecision,
    exportPrecision: explicitExpPrecision,
    formattedVisualMin,
    formattedVisualMax,
    formattedExportMin,
    formattedExportMax,
    warnings
  };
}

export interface ParameterVerificationResult {
  match: boolean;
  status: "SUCCESS" | "SUCCESS_NEAREST_BAND" | "DISPARITY" | "WARNING" | "FAIL" | "FAIL_MAPPING_CONFIGURATION" | "MISMATCH";
  reason?: string;
  warning?: string;
  isAccidentalClampingTo1: boolean;
  isMappingConfigSuspicious: boolean;
  toleranceUsed: number;
}

export function verifyParameterExportMatch(options: {
  intendedDisplayValue: string | number;
  expectedExportValue: string | number;
  actualExportValue: string | number | undefined;
  parameterDef?: ResolvedParameter | any;
  conversionResult?: ConvertParameterResult;
  isNearestBandMapping?: boolean;
  nearestBandFreq?: number;
}): ParameterVerificationResult {
  const {
    intendedDisplayValue,
    expectedExportValue,
    actualExportValue,
    parameterDef,
    conversionResult,
    isNearestBandMapping,
    nearestBandFreq,
  } = options;

  // 1. Check for missing actual export value
  if (actualExportValue === undefined || actualExportValue === "MISSING" || actualExportValue === null || String(actualExportValue).trim() === "") {
    return {
      match: false,
      status: "FAIL",
      reason: `Expected ${intendedDisplayValue} (raw: ${expectedExportValue}) but parameter "${parameterDef?.xmlName || parameterDef?.friendlyName || 'unknown'}" is missing in exported XML.`,
      warning: undefined,
      isAccidentalClampingTo1: false,
      isMappingConfigSuspicious: false,
      toleranceUsed: 0,
    };
  }

  // 2. Check for accidental continuous knob clamping down to 1
  const isKnownContinuousAmpKnob = parameterDef?.kind === "continuous_knob" || 
    (parameterDef?.max > 1 && inferParameterKind(parameterDef?.friendlyName, parameterDef?.xmlName) === "continuous_knob") ||
    (inferParameterKind(parameterDef?.friendlyName, parameterDef?.xmlName) === "continuous_knob");

  const isAccidentalClampingTo1 = !!(isKnownContinuousAmpKnob && parameterDef?.max === 1 && conversionResult?.clampApplied);

  if (isAccidentalClampingTo1) {
    return {
      match: false,
      status: "FAIL",
      reason: `Accidental continuous knob clamping: Intended display: ${intendedDisplayValue}, clamped to ${expectedExportValue} because exportMax is ${parameterDef?.max}`,
      warning: `Input value ${intendedDisplayValue} was clamped to ${expectedExportValue} because exportMax is 1. This appears invalid for a continuous amp knob.`,
      isAccidentalClampingTo1: true,
      isMappingConfigSuspicious: false,
      toleranceUsed: 0,
    };
  }

  // 3. Numeric extraction & comparison
  const nv = typeof expectedExportValue === "number" ? expectedExportValue : parseFloat(String(expectedExportValue));
  const ev = typeof actualExportValue === "number" ? actualExportValue : parseFloat(String(actualExportValue));
  const displayNum = typeof intendedDisplayValue === "number" ? intendedDisplayValue : parseFloat(String(intendedDisplayValue));

  let isMappingConfigSuspicious = false;
  let match = false;
  let toleranceUsed = 0.05;

  if (!isNaN(nv) && !isNaN(ev)) {
    // Check if actual XML value matched intended display directly but mapping wanted a drastically different value
    if (!isNaN(displayNum) && Math.abs(displayNum - ev) <= 0.15 && Math.abs(nv - ev) > 0.5 && Math.abs(displayNum) > 1e-4) {
      // Intended display equals actual exported XML, but mapping was different
      isMappingConfigSuspicious = true;
      match = false;
    } else {
      // Determine parameter scale and calculate scale-appropriate tolerance
      const expMin = parameterDef?.min ?? conversionResult?.exportMin ?? 0;
      const expMax = parameterDef?.max ?? conversionResult?.exportMax ?? Math.max(Math.abs(nv), 10);
      const span = Math.max(1e-6, Math.abs(expMax - expMin));

      if (span <= 1.05) {
        // Small linear scale e.g. [0, 1] or [0.00001, 1] (Threshold linear, Gate linear, Gain 0-1)
        toleranceUsed = 1e-4;
      } else if (span <= 12) {
        // Standard 0-10 scale
        toleranceUsed = 0.02;
      } else if (span <= 120) {
        // 0-100 percentage or dB scale (-100 to 0)
        toleranceUsed = 0.25;
      } else {
        // Large frequency or delay time scale (20 to 20000 Hz, 0 to 2000 ms)
        toleranceUsed = Math.max(1.0, span * 0.01);
      }

      // Check if one value is zero and other is non-zero (strict zero guard)
      if ((Math.abs(ev) < 1e-6 && Math.abs(nv) > 1e-4) || (Math.abs(nv) < 1e-6 && Math.abs(ev) > 1e-4)) {
        match = false;
      } else {
        const diff = Math.abs(nv - ev);
        match = diff <= toleranceUsed || String(expectedExportValue).trim().toLowerCase() === String(actualExportValue).trim().toLowerCase();
      }
    }
  } else {
    // String comparison (enums, discrete text)
    const expStr = String(expectedExportValue).trim().toLowerCase();
    const actStr = String(actualExportValue).trim().toLowerCase();
    match = expStr === actStr;
  }

  // 4. Status determination
  let status: ParameterVerificationResult["status"] = "SUCCESS";
  let reason: string | undefined = undefined;
  let warning: string | undefined = undefined;

  if (isMappingConfigSuspicious) {
    status = "FAIL_MAPPING_CONFIGURATION";
    reason = `Mapping configuration appears wrong: actual AT5 XML preserved ${ev} but current mapping expected ${nv} for ${parameterDef?.friendlyName || 'parameter'}.`;
  } else if (!match) {
    status = "FAIL";
    reason = `Expected ${intendedDisplayValue} (expected raw: ${expectedExportValue}) but exported value loads as ${conversionResult?.reverseDisplayValue || actualExportValue} (raw: "${actualExportValue}").`;
  } else if (isNearestBandMapping) {
    status = "SUCCESS_NEAREST_BAND";
    reason = `Mapped to nearest supported AT5 band ${nearestBandFreq}Hz.`;
  } else if (conversionResult?.clampApplied) {
    status = "DISPARITY";
    reason = `Value disparity (clamped): Intended: ${intendedDisplayValue}, actual exported value loads as ${conversionResult.reverseDisplayValue} due to physical limits of the gear.`;
    if (conversionResult.warnings && conversionResult.warnings.length > 0) {
      warning = conversionResult.warnings.join("; ");
    }
  } else if (conversionResult?.warnings && conversionResult.warnings.length > 0) {
    status = "WARNING";
    warning = conversionResult.warnings.join("; ");
    reason = warning;
  } else {
    status = "SUCCESS";
  }

  return {
    match,
    status,
    reason,
    warning,
    isAccidentalClampingTo1,
    isMappingConfigSuspicious,
    toleranceUsed,
  };
}

export function resolveParameterValue(
  value: unknown,
  min: number,
  max: number,
  transform?: VerifiedParamDef["transform"] | string,
  visualMin?: number,
  visualMax?: number,
  def?: any
): string | number | undefined {
  const res = convertParameterValueForExport({
    inputValue: value,
    parameterDef: def,
    conversionMode: transform,
    displayMin: visualMin,
    displayMax: visualMax,
    exportMin: min,
    exportMax: max,
    displayPrecision: def?.displayPrecision ?? def?.displayDecimalPlaces ?? def?.decimalPlaces,
    exportPrecision: def?.exportPrecision ?? def?.exportDecimalPlaces,
    exportDecimalPlaces: def?.exportPrecision ?? def?.exportDecimalPlaces,
  });

  if (typeof res.formattedExportValue === "string" && res.formattedExportValue !== "") {
    return res.formattedExportValue;
  }
  if (typeof res.finalExportValue === "number" && Number.isFinite(res.finalExportValue)) {
    return res.finalExportValue;
  }
  return undefined;
}

export function normalizeSettingsToCanonical(
  gearNameOrId: string | undefined,
  category: string,
  settings: Record<string, string | number> = {}
): Record<string, string | number> {
  const defs = getParameterDefinitions(gearNameOrId, category);
  if (!defs || defs.length === 0) {
    return settings;
  }

  const normalized: Record<string, string | number> = {};
  for (const [key, val] of Object.entries(settings)) {
    const cleanKey = key.toLowerCase().replace(/[^a-z0-9.]/g, "");
    
    const def = defs.find((d) => {
      const cleanFriendly = d.friendlyName.toLowerCase().replace(/[^a-z0-9.]/g, "");
      const cleanXml = d.xmlName.toLowerCase().replace(/[^a-z0-9.]/g, "");
      const cleanDisplay = (d.displayParameterName || "").toLowerCase().replace(/[^a-z0-9.]/g, "");
      const cleanCanonical = (d.canonicalParameterName || "").toLowerCase().replace(/[^a-z0-9.]/g, "");
      const cleanAliases = [
        ...(d.aliases ?? []),
        ...(d.savedAliases ?? []),
        ...(d.rawMappingAliases ?? []),
        ...(d.autoGeneratedAliases ?? []),
        ...(d.effectiveAliases ?? [])
      ].map((a) => a.toLowerCase().replace(/[^a-z0-9.]/g, ""));
      return (
        cleanFriendly === cleanKey ||
        cleanXml === cleanKey ||
        cleanDisplay === cleanKey ||
        cleanCanonical === cleanKey ||
        cleanAliases.includes(cleanKey)
      );
    });

    if (def) {
      normalized[def.friendlyName] = val;
    } else {
      normalized[key] = val;
    }
  }
  return normalized;
}

export function buildMappedParameterAttrs(
  gearNameOrId: string | undefined,
  category: string,
  settings: Record<string, unknown> = {}
): string {
  const defs = getParameterDefinitions(gearNameOrId, category);

  const canonicalSettings = normalizeSettingsToCanonical(gearNameOrId, category, settings as Record<string, string | number>);

  const normalisedSettings = new Map(
    Object.entries(canonicalSettings).map(([key, value]) => [normalise(key), value])
  );

  // Darrell 100 channel-aware mappings (Rule 6 & 7)
  const normGear = (gearNameOrId || "").toLowerCase().replace(/[^a-z0-9]/g, "");
  if (normGear === "darrell100") {
    let channelVal = (settings["Channel"] ?? settings["channel"] ?? settings["Channel_Darrell100"] ?? settings["channel_darrell100"]) as any;
    let isHighGainChannel = false;
    if (channelVal !== undefined) {
      const chStr = String(channelVal).toLowerCase();
      if (chStr === "2" || chStr.includes("lead") || chStr.includes("high") || chStr.includes("ch2") || chStr.includes("crunch")) {
        isHighGainChannel = true;
      }
    }

    const gainVal = (settings["Gain"] ?? settings["gain"] ?? settings["preamp"] ?? settings["PreAmp"] ?? settings["drive"] ?? settings["Drive"]) as any;
    const masterVal = (settings["Master"] ?? settings["master"] ?? settings["volume"] ?? settings["Volume"]) as any;

    if (isHighGainChannel) {
      if (gainVal !== undefined && normalisedSettings.get(normalise("Gain2_Darrell100")) === undefined) {
        normalisedSettings.set(normalise("Gain2_Darrell100"), gainVal);
      }
      if (masterVal !== undefined && normalisedSettings.get(normalise("Master2_Darrell100")) === undefined) {
        normalisedSettings.set(normalise("Master2_Darrell100"), masterVal);
      }
    } else {
      if (gainVal !== undefined && normalisedSettings.get(normalise("Gain1_Darrell100")) === undefined) {
        normalisedSettings.set(normalise("Gain1_Darrell100"), gainVal);
      }
      if (masterVal !== undefined && normalisedSettings.get(normalise("Master1_Darrell100")) === undefined) {
        normalisedSettings.set(normalise("Master1_Darrell100"), masterVal);
      }
    }

    if (channelVal !== undefined) {
      normalisedSettings.set(normalise("Channel_Darrell100"), channelVal);
    }
  }

  // Noise Gate Depth safety
  if (normalise(gearNameOrId || "") === "noise gate") {
    const hasDepth = ["depth", "reduction"].some(alias => normalisedSettings.has(normalise(alias)));
    if (!hasDepth) {
      normalisedSettings.set("depth", "-60");
    }
  }

  if (!defs.length) {
    return Object.entries(settings || {})
      .map(([key, value]) => `${compact(key)}="${escapeXmlAttr(value)}"`)
      .join(" ");
  }

  const attributes: { xmlName: string; attrValue: string; isDefault: boolean }[] = [];

  for (const def of defs) {
    const lookupNames = [
      def.friendlyName,
      def.xmlName,
      def.displayParameterName,
      def.canonicalParameterName,
      ...(def.aliases ?? []),
      ...(def.savedAliases ?? []),
      ...(def.rawMappingAliases ?? []),
      ...(def.autoGeneratedAliases ?? []),
      ...(def.effectiveAliases ?? [])
    ].filter(Boolean) as string[];
    let raw = lookupNames
      .map((name) => normalisedSettings.get(normalise(name)))
      .find((value) => value !== undefined);

    let isDefault = false;

    if (raw === undefined && gearNameOrId && (category === "rack" || category === "stomp") && gearNameOrId.toLowerCase().includes("graphic")) {
      const bandMatch = def.xmlName.match(/^Band(\d+)$/i);
      if (bandMatch) {
        const bandFreq = parseInt(bandMatch[1]);
        for (const [sKey, sVal] of normalisedSettings.entries()) {
          const hz = parseFrequencyToHz(sKey);
          if (hz !== null) {
            const closest = findClosestBand(hz);
            if (closest === bandFreq) {
              raw = sVal;
              break;
            }
          }
        }
      }
    }

    if (raw === undefined && def.defaultValue !== undefined) {
      raw = def.defaultValue;
      isDefault = true;
    }

    const resolved = resolveParameterValue(raw, def.min, def.max, def.transform, def.visualMin, def.visualMax, def);
    if (resolved === undefined) continue;

    const formattedValue = typeof resolved === "string"
      ? escapeXmlAttr(resolved)
      : String(Number(resolved.toFixed(6)));

    attributes.push({
      xmlName: def.xmlName,
      attrValue: formattedValue,
      isDefault
    });
  }

  const finalMap = new Map<string, typeof attributes[number]>();
  for (const attr of attributes) {
    const existing = finalMap.get(attr.xmlName);
    if (!existing || (existing.isDefault && !attr.isDefault)) {
      finalMap.set(attr.xmlName, attr);
    }
  }

  return Array.from(finalMap.values())
    .map(attr => `${attr.xmlName}="${attr.attrValue}"`)
    .join(" ");
}

export interface TestTranslationResult {
  inputValue: string | number;
  parsedNumericValue?: number | string;
  resolvedExportValue: string | number;
  conversionMode: string;
  isClamped: boolean;
  displayPrecision?: number;
  exportPrecision?: number;
  visualRange: { min: number; max: number; unit?: string; formattedMin?: string; formattedMax?: string };
  exportRange: { min: number; max: number; formattedMin?: string; formattedMax?: string };
  formulaDescription?: string;
  xmlPreview: string;
  reverseConvertedDisplayValue?: string;
  warnings?: string[];
}

export function testSingleParameterTranslation(
  paramDef: any,
  inputValue: string | number,
  gearContext?: { gearType?: string; gearDisplayName?: string; gearGuid?: string }
): TestTranslationResult {
  const warnings: string[] = [];

  const xmlAttr = paramDef.export?.name || paramDef.at5XmlAttributeName || paramDef.canonicalName || paramDef.displayName || paramDef.xmlName || "Param";
  const convMode = paramDef.conversion?.mode || paramDef.translationMode || paramDef.transform || paramDef.conversion || "direct";

  const res = convertParameterValueForExport({
    inputValue,
    parameterDef: paramDef,
    conversionMode: convMode,
    displayMin: paramDef.visual?.min ?? paramDef.displayMin ?? paramDef.visualMin,
    displayMax: paramDef.visual?.max ?? paramDef.displayMax ?? paramDef.visualMax,
    exportMin: paramDef.export?.min ?? paramDef.exportMin ?? paramDef.min,
    exportMax: paramDef.export?.max ?? paramDef.exportMax ?? paramDef.max,
    displayUnit: paramDef.visual?.unit ?? paramDef.displayUnit ?? paramDef.unit,
    displayPrecision: paramDef.displayPrecision ?? paramDef.displayDecimalPlaces ?? paramDef.decimalPlaces,
    exportPrecision: paramDef.exportPrecision ?? paramDef.exportDecimalPlaces,
    exportDecimalPlaces: paramDef.exportPrecision ?? paramDef.exportDecimalPlaces
  });

  if (!paramDef.export?.name && !paramDef.at5XmlAttributeName && !paramDef.xmlName) {
    warnings.push("No explicit AT5 XML attribute ID configured.");
  }

  // Check for bad / suspicious mapping configuration
  if (res.conversionMode === "db_to_linear" || paramDef.parameterKind === "gain_db") {
    if ((res.displayMin === res.exportMin && res.displayMax === res.exportMax) || (res.displayMin >= 0 && res.displayMax > 1 && res.displayMax <= 10)) {
      warnings.push(
        `CHECK / FAIL_MAPPING_CONFIGURATION: Visual range [${res.displayMin}, ${res.displayMax}] appears to contain raw AmpliTube float values. For db_to_linear, set UI Visual range to display dB values (e.g. -15 to +15 dB).`
      );
    }
  }

  if (res.warnings && res.warnings.length > 0) {
    warnings.push(...res.warnings);
  }

  const xmlPreview = `${xmlAttr}="${escapeXmlAttr(res.formattedExportValue)}"`;

  return {
    inputValue,
    parsedNumericValue: res.parsedNumericValue,
    resolvedExportValue: res.formattedExportValue,
    conversionMode: res.conversionMode,
    isClamped: res.clampApplied,
    displayPrecision: res.displayPrecision,
    exportPrecision: res.exportPrecision,
    visualRange: {
      min: res.displayMin,
      max: res.displayMax,
      unit: res.displayUnit,
      formattedMin: res.formattedVisualMin,
      formattedMax: res.formattedVisualMax
    },
    exportRange: {
      min: res.exportMin,
      max: res.exportMax,
      formattedMin: res.formattedExportMin,
      formattedMax: res.formattedExportMax
    },
    formulaDescription: paramDef.conversion?.formula || paramDef.helperDescription,
    xmlPreview,
    reverseConvertedDisplayValue: res.reverseDisplayValue,
    warnings: warnings.length > 0 ? warnings : undefined
  };
}
